### ISSUE TITLE
maildir write support?

### ISSUE THREAD

**Issue by dario23** [staktrace/maildir#1]
hi,

would you be willing to implement/accept pull requests implementing basic write support, i.e. storing new messages to a maildir? probably that would mean some new dependencies for gathering system info/random for a unique filename as described e.g. at [https://cr.yp.to/proto/maildir.html](https://cr.yp.to/proto/maildir.html). on the other hand i would be willing to put work into that :)

**Comment by staktrace** [comment]
Yeah I would accept pull requests for that. Please try to keep the set of dependencies as small as possible though. Obviously no need to reimplement things like random number generators but when choosing crates to depend on, consider the number of recursive dependencies being pulled in.
