### ISSUE TITLE
Repository should contain license text

### ISSUE THREAD

**Issue by rotty** [staktrace/maildir#10]
It would be good to have the complete license text in the repository, mainly to make it extra clear what the chosen license is.

**Comment by staktrace** [comment]
I'm kind of the fence about this. I've had to deal with vendoring rust crates at my day job and when a crate has both a LICENSE text file and a license identifier in the Cargo.toml it's not always clear which one takes precedence.

**Comment by staktrace** [comment]
For your use case, is there a reason having 0BSD as the license specified in the Cargo.toml file is not sufficiently clear?

**Comment by rotty** [comment]
> I'm kind of the fence about this. I've had to deal with vendoring rust crates at my day job and when a crate has both a LICENSE text file and a license identifier in the Cargo.toml it's not always clear which one takes precedence.

Isn't that only an issue if these are actually not in agreement?

**Comment by rotty** [comment]
> For your use case, is there a reason having 0BSD as the license specified in the Cargo.toml file is not sufficiently clear?

It's actually ok for me ATM, but my impression was that the current (best?) practice is to include the license text in the source code repository (which will cause it appearing in the published crate as well); at least I never encountered a crate where I noticed the license text missing. IANAL, but distributing code with a desired license, but without actually including the license text seems a bit dubious to me.

**Comment by staktrace** [comment]
After giving it some thought I decided that you're right, it's better to include the license text. I'll fix. Thanks for bringing this up!
