### ISSUE TITLE
Support listing mails by "info" flags

### ISSUE THREAD

**Issue by darnir** [staktrace/maildir#11]
The [Maildir Spec](https://cr.yp.to/proto/maildir.html) supports adding flags to the filename of the emails in the directory.

Quoting the page here:

>  info starting with "2,": Each character after the comma is an independent flag.
> 
>     Flag "P" (passed): the user has resent/forwarded/bounced this message to someone else.
>     Flag "R" (replied): the user has replied to this message.
>     Flag "S" (seen): the user has viewed this message, though perhaps he didn't read all the way through it.
>     Flag "T" (trashed): the user has moved this message to the trash; the trash will be emptied by a later user action.
>     Flag "D" (draft): the user considers this message a draft; toggled at user discretion.
>     Flag "F" (flagged): user-defined flag; toggled at user discretion. 
> 
> New flags may be defined later. Flags must be stored in ASCII order: e.g., "2,FRS". 

Would you be willing to accept code that provided a method for listing mails in a Maildir based on these flags?

**Comment by staktrace** [comment]
Can't you already do that by filtering the MailEntries iterator? The entry objects have functions to expose the flags. What would your proposed function do differently?

**Comment by darnir** [comment]
You're right, I can. I opened the issue when I couldn't find anything in the API docs for `Maildir`. Should have read the docs for `MailEntry` first.
