### ISSUE TITLE
API Questions: flags and store 

### ISSUE THREAD

**Issue by dcermak** [staktrace/maildir#12]
Hi, I'm currently implementing an email synchronizer in rust and wanted to dump email that I fetch via IMAP into Maildir, for which I am using this crate (thanks for all your work on this btw!).

I've hit a few issues/questions though:
- I'd like to store emails that I download via IMAP in Maildir and keep track of their Maildir ID. Unfortunately neither `Maildir::store_new` nor `Maildir::store_cur_with_flags` support that (they don't return the message ID). Would you consider changing the APi to support that? This should be a relatively simple change in `Maildir::store()`.
- Is there a particular reason why flags are handled as `&str` (beside obviously simplicity) and not as a enum?

P.S.: from another Rust newbie: I've found this crate pleasant to work with so far :)

**Comment by staktrace** [comment]
Thanks for the PR! Yes, that API change makes sense and I'm happy to accept it.

With respect to the flags being a `&str` - the [spec](https://cr.yp.to/proto/maildir.html) says that additional flags can be defined later, and I expect different implementations might already have their own flags that are perhaps even incompatible (e.g. app X might use flag 'Z' for something, and app Y might use flag 'Z' for something else). To maximize compatibility I chose not to use an enum and allow the user of the library access to the raw flag strings instead.

**Comment by dcermak** [comment]
> With respect to the flags being a `&str` - the [spec](https://cr.yp.to/proto/maildir.html) says that additional flags can be defined later, and I expect different implementations might already have their own flags that are perhaps even incompatible (e.g. app X might use flag 'Z' for something, and app Y might use flag 'Z' for something else). To maximize compatibility I chose not to use an enum and allow the user of the library access to the raw flag strings instead.

That makes perfect sense, thanks for the explanation! Incidentally I stumbled over dovecot's documentation where they explain that they allow up to 26 user defined tags, which are stored as the lowercase letters of the English alphabet. Using an `enum` then would be relatively cumbersome.

**Comment by staktrace** [comment]
Fixed by #13. I don't think there's anything outstanding here, please correct me if I'm wrong.

**Comment by dcermak** [comment]
No there isn't, thanks for your quick reply & merge!
