### ISSUE TITLE
RFD: Should this crate to offer mail parsing functionality?

### ISSUE THREAD

**Issue by rotty** [staktrace/maildir#14]
In principle, the functionality in this library can be used with any crate that provides a parser for email messages; I thus wonder if it would make sense to discuss whether coupling this crate to `mailparse` makes sense; the Maildir format is only about the directory layout, and does not really dictate the message format; quoting from [maildir(5)](http://www.qmail.org/qmail-manual-html/man5/maildir.html):

> The message is normally in RFC 822   format,   starting  with  a  Return-Path  line  and  a Delivered-To line, but it  could  contain  arbitrary  binary  data.  It might not even end with a newline.

If implemented, this proposal would remove a few methods from `MailEntry`, and in return giving the crate a more clearly delineated scope of responsibility, and not imply users should use `mailparse` for dealing with message content.

**Comment by staktrace** [comment]
It's not totally clear to me what you're suggesting. If you're proposing decoupling `maildir` from `mailparse` so that users can use the former without dragging in the latter, then yes I think that's a reasonable thing. The way I would like to see it done would be to add a feature to the crate that is disabled by default and contains all the `mailparse` dependency stuff. That way existing users who do use the APIs that require `mailparse` can still access those by adding the feature.

**Comment by rotty** [comment]
> It's not totally clear to me what you're suggesting. If you're proposing decoupling `maildir` from `mailparse` so that users can use the former without dragging in the latter, then yes I think that's a reasonable thing.

Yes, that was exactly what I was suggesting. My motivation is that I'm (slowly) working on a mail filter (akin to [scmail](http://0xcc.net/scmail/)), which will have its own incremental parser, and I'd like to use the maildir crate.

> The way I would like to see it done would be to add a feature to the crate that is disabled by default and contains all the `mailparse` dependency stuff. That way existing users who do use the APIs that require `mailparse` can still access those by adding the feature.

I didn't think of using a feature flag; that would surely work, giving the advantages you mention (backwards compatibility). OTOH, it would make the code more complex; and I'm not sure it's warranted in this case. It seems the [Cargo manual](https://doc.rust-lang.org/cargo/reference/manifest.html) agrees; in *The `[features]` section*, it states:

> In most cases, the concept of optional dependency in a library is best expressed as a separate package that the top-level application depends on.
> [...]
> In almost all cases, it is an antipattern to use these features outside of high-level packages that are designed for curation. If a feature is optional, it can almost certainly be expressed as a separate package.

The advantage I see with (eventually) completely decoupling `maildir` and `mailparse` would be that it's much clearer what crate does what; for example, I don't think the functionality of `MailEntry::received()` belongs into the `maildir` crate -- this should be, IMHO, the concern of the mail parser, or of a crate that offers convenience functionality on top of a mail parser. Of course, if you decide to leave the crates coupled, you could provide a wrapper `MailEntry::received()` in `maildir`, which calls into some `mailparse` functionality, but does that wrapper really buy you much in terms of ergonomics?

My top-of-the-head proposal would be to:

1. Introduce functionality for reading mail directly from disk into `mailparse`, so it can be more easily used given not a byte slice, but a `Path`. This would essentially move the part of of `maildir::MailEntry` which keeps (and accesses) the data to `mailparse`.
2. Introduce the feature flag into `maildir`, enabled by default, as you suggested, in the same instance deprecating all the methods in `MailEntry` which depend on `data`.
3. On the next API-breaking release of `maildir`, drop the `mailparse` dependency completely.

Of course, this all hinges on getting the ergonomics right, such that it's not really more incovenient to get at the deprecated/removed functionality.

*Edit: missing words*

**Comment by rotty** [comment]
Of course, code speaks clearer than human words, so if you indicate that you are open to that idea, I'd prepare a PR to implement (1), which should be an improvement of `mailparse`, regardless of whether steps (2) and (3) are followed through.

**Comment by staktrace** [comment]
(1) sounds reasonable enough, feel free to submit a PR for that. Off the top of my head I'm a little unsure what it would look like given the lifetime setup that `mailparse` currently uses so if you find the change is getting nontrivial please check back with me before going too deep.

With respect to (2) and (3) I'm not opposed to breaking the dependency entirely provided it's not significantly harder for downstream crates to keep their existing functionality. I'd be happy to review a PR for those changes and iterate on the details. But let's do (1) first, as you suggested.

**Comment by rotty** [comment]
I'm not sure when I'll come around to submitting a PR to `mailparse`, and this discussion is pretty much settled anyway for now, so I'll close this. I'll make sure to reference this issue when submitting the discussed `mailparse` PR.
