### ISSUE TITLE
Update mailparse

### ISSUE THREAD

**Issue by lewisdiamond** [staktrace/maildir#18]
Could you please make a release with the updated mailparse version?

Thanks

**Comment by staktrace** [comment]
You should be able to specify the latest mailparse version in your downstream Cargo.toml. Which you should be doing anyway if you're relying on a specific mailparse version.

**Comment by staktrace** [comment]
Closing for now, let me know if for some reason what I suggested doesn't work for you.

**Comment by lewisdiamond** [comment]
That's what I had and it did not compile:
```
^^^^^^^^ expected struct `mailparse::ParsedMail`, found a different struct `mailparse::ParsedMail`
note: Perhaps two different versions of crate `mailparse` are being used?
```

Using maildir git master fixed the issue for me (master uses 0.8, the crate uses 0.6).

**Comment by staktrace** [comment]
Ah, my mistake. I thought the published version already had the latest mailparse dependency. I've republished now, maildir 0.2.0 uses mailparse 0.8. Thanks for bringing this to my attention!

**Comment by lewisdiamond** [comment]
Thanks, I'll update on my side.
