### ISSUE TITLE
Should not expose `nix::Error` in public API

### ISSUE THREAD

**Issue by rotty** [staktrace/maildir#20]
I just wanted to send a pull request to update the `nix` dependency to 0.16. While it compiled without any code changes, I noticed this would be a breaking change, as the `nix::Error` is exposed via the publicly-accessible `MaildirError::Nix` variant, and via the `From<nix::Error>` trait impl for `MaildirError`. 

I would hence propose to change `MaildirError` in a way that no longer exposes `nix::Error` as part of the public API; that might involve making it opaque, similar to `std::io::Error`, or by eliminating the `MaildirError::Nix` variant completely -- `nix::Error` has large overlap with `std::io::Error`, so it may make sense to just map it to `io::Error`.

What do you think?

**Comment by staktrace** [comment]
I was actually just looking at the dependency on `nix` yesterday and was thinking that I can remove the dependency entirely. Effectively the only reason it's used to generate some randomness and there's other sources I can use to generate that without pulling in `nix`, and still be compatible with the maildir "specification". So I can just do that instead (probably sometime later today).

**Comment by rotty** [comment]
Thanks for the quick response and thorough fix!
