### ISSUE TITLE
feature flag gethostname

### ISSUE THREAD

**Issue by alexwennerberg** [staktrace/maildir#24]
Hi, I use maildir as a dependency for https://git.alexwennerberg.com/crabmail/ and I'm trying to minimize the dependency tree. I don't use the part of this library that uses gethostname (and therefore libc) -- is there any way you could feature flag this functionality so I don't require the dependency? I could put together a PR for this as well

Alex

**Comment by staktrace** [comment]
I only skimmed your code but from [the looks of it](https://git.alexwennerberg.com/crabmail/file/src/main.rs.html#l575) your usage of `maildir` is quite minimal. If you want to trim the dependency tree you might as well just inline the relevant code and not use `maildir` at all. You really just need to list all files in `cur` and `new`, skipping ones that start with `.` and feed them into `mailparse`. Doesn't look like you're using the flags or any of the other functions so it should be pretty simple. Is there a reason you don't want to do that?

**Comment by alexwennerberg** [comment]
That makes sense. Tbf I didn’t look much into the maildir crate beyond the function I am using. I’ll move the relevant code into my crate. Ty

Alex

**Comment by staktrace** [comment]
Closing for now; let me know if you run into problems.
