### ISSUE TITLE
Maildir++ folder feature

### ISSUE THREAD

**Issue by soywod** [staktrace/maildir#25]
First of all, thanks for your great libs around emails. I'm already using `mailparse`, and now I'm using `maildir` for my project ([a CLI email client](https://github.com/soywod/himalaya)). I try to build a common interface between different email backends like IMAP, POP, Maildir, Notmuch etc. I started with IMAP and Maildir, here what I've got so far:

```rust
pub trait BackendService<'a> {
    fn connect(&mut self) -> Result<()>;
    fn get_mboxes(&mut self) -> Result<Mboxes>;
    fn get_envelopes(&mut self, mbox: &str, filter: &str, sort: &str, page_size: usize, page: usize) -> Result<Envelopes>;
    fn add_msg(&mut self, mbox: &str, msg: &[u8], flags: &str) -> Result<String>;
    fn get_msg(&mut self, mbox: &str, id: &str) -> Result<Msg>;
    fn copy_msg(&mut self, mbox_source: &str, mbox_target: &str, id: &str) -> Result<()>;
    fn move_msg(&mut self, mbox_source: &str, mbox_target: &str, id: &str) -> Result<()>;
    fn del_msg(&mut self, mbox: &str, ids: &str) -> Result<()>;
    fn add_flags(&mut self, mbox: &str, ids: &str, flags: &str) -> Result<()>;
    fn set_flags(&mut self, mbox: &str, ids: &str, flags: &str) -> Result<()>;
    fn del_flags(&mut self, mbox: &str, ids: &str, flags: &str) -> Result<()>;
    fn disconnect(&mut self) -> Result<()>;
}
```

The 3 I have issue with are `get_mboxes`, `copy_msg` and `move_msg`, because they don't exist with Maildir. However, the [Maildir++](http://www.courier-mta.org/imap/README.maildirquota.html) extension allow the usage of other folders/mailboxes (if they start by a dot, like `.Sent` or `.Draft`). Can I propose a PR to support the folder feature of Maildir++?

**Comment by staktrace** [comment]
I'm not opposed to adding some methods to the library if it will help, but I think you should be able to implement your backend with the existing API exposed by `maildir`. For example, `get_mboxes` would be implemented by calling `path()` and then iterating the entries to find subfolders that start with `.`. `copy_msg` and `move_msg` could also be implemented by simply copying/moving files. Is there some reason this doesn't work?

I wouldn't mind implementing the Maildir++ extension but then I'd want to implement the whole extension (folders and quotas) which would probably change the API somewhat.

**Comment by soywod** [comment]
> but I think you should be able to implement your backend with the existing API exposed by `maildir`

Totally agree. For me it does not change anything: I will have to develop sth. But I though it could be nice to integrate those features inside `maildir`, so other users can benefit from it.

> but then I'd want to implement the whole extension (folders and quotas)

Well, this is not mandatory. I mean, you can just propose folders but not quotas, they are totally independent features.

> which would probably change the API somewhat

I thought about an implementation that would not break the current API, sth like this:

1. Introducing a new struct `MaildirEntries`
2. Implementing the `Iterator` trait for it, where the `Item` type is a `std::io::Result<Maildir>`
3. Add new function to the `Maildir` struct:

```rust
pub fn list_subdirs(&self) -> MaildirEntries;
pub fn copy_to(&self, id: &str, target: &Maildir) -> std::io::Result<()>;
pub fn move_to(&self, id: &str, target: &Maildir) -> std::io::Result<()>;
```

What do you think? I can propose a PR very soon if you are interested in.

**Comment by staktrace** [comment]
Yeah ok, that seems reasonable enough. Note that the spec you linked also says that recursive folders are not supported but IMO that's a silly restriction and I'm ok with the API you proposed which would not have this restriction.

**Comment by soywod** [comment]
PR ready for review!
