### ISSUE TITLE
Memmap is unmaintained

### ISSUE THREAD

**Issue by MTRNord** [staktrace/maildir#30]
Hi I just got https://github.com/erooster-mail/erooster/issues/36 on my repo as memmap is unmaintained according to https://github.com/danburkert/memmap-rs/issues/90

And this lib is pulling it in.
 I was wondering if there is any chance that maildir could move to a maintained crate for the memmap feature :)

**Comment by MTRNord** [comment]
I provided a companion PR for this at #31

**Comment by staktrace** [comment]
Thank you for the PR! I'll push out a new release later today

**Comment by MTRNord** [comment]
Thanks a lot for merging it already :)

On that note also thanks for making this crate! Really helped a lot while developing my smtp+imap server :D
