### ISSUE TITLE
Add cargo feature to make mailparse optional

### ISSUE THREAD

**Issue by soywod** [staktrace/maildir#35]
Here the use case: I would like to use `maildir` to interact with a Maildir folder but I would like to use another crate than `mailparse` for parsing emails. Would you agree to add a cargo feature to achieve this aim? I can propose a PR. Thank you!

**Comment by staktrace** [comment]
Hmm that seems like it would be quite an invasive change since this crate directly uses a bunch of types from `mailparse`. I think it would probably be better to fork this crate and switch the fork to use whatever other crate you want.

**Comment by soywod** [comment]
Alright, thank you for your reply :slightly_smiling_face:
