### ISSUE TITLE
Reading a message requires a mutable reference

### ISSUE THREAD

**Issue by WhyNotHugo** [staktrace/maildir#37]
I'm trying to use maildir with [`skim`](https://github.com/lotabout/skim) to pick emails. However, I'm kind of stuck due to the fact that the [method that reads headers](https://docs.rs/maildir/latest/maildir/struct.MailEntry.html#method.headers) requires a _mutable_ reference.

The issue lies mostly in the context of converting a message into a string (e.g.: `skim::SkimItem`) I only have a non-mutable reference to the message. This makes sense; creating a text-based representation of an item does not need to mutate it.

I see the same applies for most methods that **read** a message: the require a mutable reference. I think the main issue lies in the fact that `read_data()` actually mutates the message. Probably returning the data (instead of assigning to `self.data`) should work.

**Comment by staktrace** [comment]
Your message is somewhat confusing. This crate is for reading an entire directory of mail files. If you want to parse individual mail messages that you already have as strings maybe you should be using the mailparse crate instead.

If you disagree please provide a link to your code so I can better understand what you're trying to do.

**Comment by WhyNotHugo** [comment]
I'm currently rewriting a lot of this code so don't have anything that works to show, but basically I have a type:

```rust
struct Message {
    inner: maildir::MailEntry,
}
```

And I want to implement [skim::SkimItem](https://docs.rs/skim/0.10.4/skim/trait.SkimItem.html) for this type. I basically need to implement a function that takes a non-mutable instance, and I need to return a string representation for it (e.g.: `fn text(&self) -> Cow<'_, str>`).

However, in order to *read* the headers of `MailEntry`, I'd need a mutable reference, which is not available in the scope of a this function. I really don't think it makes sense to require a _mutable_ reference to an entry in order to read it, because reading should be a read-only operation.

**Comment by soywod** [comment]
I had the same issue within my project. The mutability is needed because the `MailEntry` holds a lazy `mailparse::ParsedMail` which leads to several issues:

- Everything relying on `read_data()` or `parsed()` needs to borrow self as mut
- Every entry parses its full content (headers and body), even when listing, which leads to perfs issues (although the `mmap` feature fixes it)
- It is not possible to change the email parser (see #35)

So, *for my needs*, I created a [fork](https://git.sr.ht/~soywod/pimalaya/tree/master/item/maildir++/README.md) [[sources](https://git.sr.ht/~soywod/pimalaya/tree/master/item/maildir++/src/lib.rs)] that removes mutable borrows and removes the email parsing (which shifts the parsing responsibility to the lib consumer, I find more flexible). Entries expose raw headers in a function and raw body in another, which fixes the perfs issues. @staktrace if you are interested in those changes I could propose a PR. Anyway, for now I stick to my fork because it fits better my needs. Thank you for your great work on this lib :pray:

**Comment by WhyNotHugo** [comment]
Right, I see. `self.data` is used as an internal "cache" for situations where other methods will be called.

I'm not convinced that this is a good idea; it implies that the caching cost (both runtime and complexity) has to be paid in any scenarios, even scenarios where the file is read only once.

It would be simpler to _not_ cache inside `MailEntry` and let consumers use `MailEntry::parsed` instead (where they can keep their data on a cache on their side as needed)?

**Comment by soywod** [comment]
> It would be simpler to _not_ cache inside `MailEntry` and let
> consumers use `MailEntry::parsed` instead (where they can keep their
> data on a cache on their side as needed)?

Yes I agree on this. My fork goes even further by not providing a
`parsed()` method but a `headers()` and a `body()` ones that just return
a `Vec<u8>`. This way consumers have free hands on how to parse emails
(mailparse, mail_parser, custom…).

**Comment by WhyNotHugo** [comment]
Yeah, I guess calling `mailparse` myself isn't too tricky either. Iterating the maildir is just a matter of:

```rs
    let maildir = PathBuf::from("/home/hugo/maildirs/drafts");
    let messages = {
        let cur = maildir.join("cur");
        let new = maildir.join("new");

        cur.read_dir()?.chain(new.read_dir()?)
    };
```

**Comment by WhyNotHugo** [comment]
FWIW, I'm only just reading (and printing) the subjects to pipe them to fzf, so perhaps my use-case it too minimal for any such library.

**Comment by soywod** [comment]
> Yeah, I guess calling `mailparse` myself isn't too tricky
> either. Iterating the maildir is just a matter of:

If you just need to read email headers then yes, iterate over folders
and open files is enough. The maildir crate makes sense when you need to
manage emails (create, read, copy, move, delete…).

**Comment by staktrace** [comment]
Sorry for the delay in responding - but yes, it sounds like your use case is simple enough that you don't even need this library. I understand that the API makes it a bit harder to use for some use cases but at the present time I'm not really able to invest more time into changing it and updating my usages of it in my own stuff. I do encourage forking this lib if it doesn't work for you as-is and am more than happy to point people to forks that have a different API.
